In [36]:
import pandas as pd
import numpy as np

Each line of vents is given as a line segment in the format x1,y1 -> x2,y2 where x1,y1 are the coordinates of one end the line segment and x2,y2 are the coordinates of the other end. These line segments include the points at both ends. In other words:

    An entry like 1,1 -> 1,3 covers points 1,1, 1,2, and 1,3.
    An entry like 9,7 -> 7,7 covers points 9,7, 8,7, and 7,7.

For now, only consider horizontal and vertical lines: lines where either x1 = x2 or y1 = y2.

To avoid the most dangerous areas, you need to determine the number of points where at least two lines overlap. In the above example, this is anywhere in the diagram with a 2 or larger - a total of 5 points.

Consider only horizontal and vertical lines. At how many points do at least two lines overlap?

In [25]:
lines = []
with open("day5.txt", "r", encoding="utf-8") as fh:
    for line in fh:
        start, end = line.split(" -> ")
        lines.append(tuple(map(int, start.split(",") + end.split(","))))

In [26]:
lines[:10]

[(644, 38, 644, 265),
 (941, 468, 941, 89),
 (807, 552, 618, 363),
 (896, 510, 896, 744),
 (227, 909, 227, 745),
 (24, 66, 946, 988),
 (563, 529, 563, 270),
 (894, 707, 359, 172),
 (146, 253, 146, 569),
 (544, 683, 140, 683)]

In [27]:
len(lines)

500

In [28]:
horizontal_or_vertial_lines = [l for l in lines if l[0] == l[2] or l[1] == l[3]]

In [29]:
horizontal_or_vertial_lines[:10]

[(644, 38, 644, 265),
 (941, 468, 941, 89),
 (896, 510, 896, 744),
 (227, 909, 227, 745),
 (563, 529, 563, 270),
 (146, 253, 146, 569),
 (544, 683, 140, 683),
 (755, 612, 755, 463),
 (394, 320, 891, 320),
 (68, 616, 68, 628)]

In [30]:
len(horizontal_or_vertial_lines)

324

In [172]:
min_x, max_x = min([min([l[0], l[2]]) for l in horizontal_or_vertial_lines]), max([max([l[0], l[2]]) for l in horizontal_or_vertial_lines])
min_y, max_y = min([min([l[1], l[3]]) for l in horizontal_or_vertial_lines]), max([max([l[1], l[3]]) for l in horizontal_or_vertial_lines])

min_x, min_y, max_x, max_y

(12, 11, 989, 989)

In [173]:
board = np.zeros((max_x + 1 - min_x, max_y + 1 - min_y))
board.shape

(978, 979)

In [174]:
for line in horizontal_or_vertial_lines:
    x1, y1, x2, y2 = line[0] - min_x, line[1] - min_y, line[2] - min_x, line[3] - min_y  # coordinates between 0 and 979
    
    if x1 > x2:
        x1, x2 = x2, x1
    
    if y1 > y2:
        y1, y2 = y2, y1    
    
    board[y1:y2+1, x1:x2+1] += 1

In [175]:
board

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [176]:
(board >= 2).sum()

5632

Part Two

Unfortunately, considering only horizontal and vertical lines doesn't give you the full picture; you need to also consider diagonal lines.

Because of the limits of the hydrothermal vent mapping system, the lines in your list will only ever be horizontal, vertical, or a diagonal line at exactly 45 degrees. In other words:

    An entry like 1,1 -> 3,3 covers points 1,1, 2,2, and 3,3.
    An entry like 9,7 -> 7,9 covers points 9,7, 8,8, and 7,9.


In [177]:
min_x, max_x = min([min([l[0], l[2]]) for l in lines]), max([max([l[0], l[2]]) for l in lines])
min_y, max_y = min([min([l[1], l[3]]) for l in lines]), max([max([l[1], l[3]]) for l in lines])

min_x, min_y, max_x, max_y

(10, 10, 989, 989)

In [178]:
board = np.zeros((max_x + 1 - min_x, max_y + 1 - min_y))
board.shape

(980, 980)

In [179]:
for line in lines:
    x1, y1, x2, y2 = line[0] - min_x, line[1] - min_y, line[2] - min_x, line[3] - min_y  # coordinates between 0 and 979
            
    if x1 != x2 and y1 != y2:
        xx = np.linspace(x1, x2, abs(x1 - x2) + 1).astype(int)
        yy = np.linspace(y1, y2, abs(y1 - y2) + 1).astype(int)
                    
        board[yy, xx] += 1  # only change diagonals
    else:    
        if x1 > x2:
            x1, x2 = x2, x1
    
        if y1 > y2:
            y1, y2 = y2, y1    
            
        board[y1:y2+1, x1:x2+1] += 1  # only change one row or column

In [180]:
board

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [181]:
(board >= 2).sum()

22213

In [182]:
x = np.random.rand(5,5)
x

array([[0.54569041, 0.84555697, 0.96286084, 0.28001758, 0.91868333],
       [0.36444798, 0.77880055, 0.25932984, 0.88587709, 0.23455367],
       [0.70357061, 0.72887378, 0.61538336, 0.09030853, 0.3101024 ],
       [0.30442185, 0.43623131, 0.29948812, 0.40994503, 0.98694304],
       [0.80430659, 0.77137011, 0.02875037, 0.16620132, 0.82062312]])

In [116]:
x[1:3,3:1]

array([], shape=(2, 0), dtype=float64)

In [144]:
np.linspace(3,1, 3)

array([3., 2., 1.])