In [1]:
import numpy as np
import pandas as pd

In [188]:
input_ = np.array(list(map(list, open("day11.txt", "r", encoding="utf-16").read().strip().splitlines())), dtype=int)

In [189]:
input_

array([[8, 5, 7, 7, 2, 4, 5, 5, 4, 7],
       [1, 6, 5, 4, 3, 3, 3, 6, 5, 3],
       [5, 3, 6, 5, 6, 3, 3, 7, 8, 5],
       [1, 3, 3, 3, 2, 4, 3, 2, 2, 6],
       [4, 2, 7, 2, 3, 8, 5, 1, 6, 5],
       [5, 6, 8, 8, 3, 2, 8, 4, 3, 2],
       [3, 1, 7, 5, 6, 3, 4, 2, 5, 4],
       [6, 7, 7, 5, 1, 4, 2, 2, 2, 7],
       [6, 1, 5, 2, 7, 2, 1, 4, 1, 5],
       [2, 6, 7, 8, 2, 2, 7, 3, 2, 5]])

In [185]:
demo_input = np.array(list(map(list, """5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526""".splitlines())), dtype=int)

In [186]:
demo_input

array([[5, 4, 8, 3, 1, 4, 3, 2, 2, 3],
       [2, 7, 4, 5, 8, 5, 4, 7, 1, 1],
       [5, 2, 6, 4, 5, 5, 6, 1, 7, 3],
       [6, 1, 4, 1, 3, 3, 6, 1, 4, 6],
       [6, 3, 5, 7, 3, 8, 5, 4, 7, 8],
       [4, 1, 6, 7, 5, 2, 4, 6, 4, 5],
       [2, 1, 7, 6, 8, 4, 1, 7, 2, 1],
       [6, 8, 8, 2, 8, 8, 1, 1, 3, 4],
       [4, 8, 4, 6, 8, 4, 8, 5, 5, 4],
       [5, 2, 8, 3, 7, 5, 1, 5, 2, 6]])

In [173]:
def update_adjacent_octopus(input_, x, y):
    n_rows, n_cols = input_.shape
    adjacent_cells = []
    move_left = False
    move_right = False
    move_up = False
    move_down = False
    
    if x > 0:
        move_left = True
    if x < n_cols - 1:
        move_right = True
    if y > 0:
        move_down = True
    if y < n_rows - 1:
        move_up = True
        
    if move_left:
        adjacent_cells.append((x-1,y))
        if move_up:
            adjacent_cells.append((x-1,y+1))
        if move_down:
            adjacent_cells.append((x-1,y-1))
    if move_right:
        adjacent_cells.append((x+1,y))
        if move_up:
            adjacent_cells.append((x+1,y+1))
        if move_down:
            adjacent_cells.append((x+1,y-1))
    if move_up:
        adjacent_cells.append((x,y+1))
    if move_down:
        adjacent_cells.append((x,y-1))
        
    for cell in adjacent_cells:
        input_[cell] += 1
    input_[x,y] = -1000

The energy level of each octopus is a value between 0 and 9. Here, the top-left octopus has an energy level of 5, the bottom-right one has an energy level of 6, and so on.

You can model the energy levels and flashes of light in steps. During a single step, the following occurs:

- First, the energy level of each octopus increases by 1.
- Then, any octopus with an energy level greater than 9 flashes. This increases the energy level of all adjacent octopuses by 1, including octopuses that are diagonally adjacent. If this causes an octopus to have an energy level greater than 9, it also flashes. This process continues as long as new octopuses keep having their energy level increased beyond 9. (An octopus can only flash at most once per step.)
- Finally, any octopus that flashed during this step has its energy level set to 0, as it used all of its energy to flash.


In [130]:
# single step
# phase 1
demo_input += 1
total_flashes = 0
# phase 2
while True:
    flashing_octopus = np.argwhere(demo_input > 9)
    
    if not flashing_octopus.size:
        break
        
    for cell in flashing_octopus:
        update_adjacent_octopus(demo_input, *cell)

# phase 3
flashing_octopus = np.argwhere(demo_input < 0)
total_flashes += flashing_octopus.size
demo_input = np.where(demo_input < 0, 0, demo_input)
print(demo_input)

[[0 0 5 0 9 0 0 8 6 6]
 [8 5 0 0 8 0 0 5 7 5]
 [9 9 0 0 0 0 0 0 3 9]
 [9 7 0 0 0 0 0 0 4 1]
 [9 9 3 5 0 8 0 0 6 3]
 [7 7 1 2 3 0 0 0 0 0]
 [7 9 1 1 2 5 0 0 0 9]
 [2 2 1 1 1 3 0 0 0 0]
 [0 4 2 1 1 2 5 0 0 0]
 [0 0 2 1 1 1 9 0 0 0]]


In [149]:
print("0:", demo_input)
total_flashes = 0
for i in range(1, 101):
    demo_input += 1
    # phase 2
    while True:
        flashing_octopus = np.argwhere(demo_input > 9)

        if not flashing_octopus.size:
            break

        for cell in flashing_octopus:
            update_adjacent_octopus(demo_input, *cell)

    # phase 3
    flashing_octopus = np.argwhere(demo_input < 0)
    total_flashes += len(flashing_octopus)
    demo_input = np.where(demo_input < 0, 0, demo_input)
    print(f"{i}:", demo_input)

0: [[5 4 8 3 1 4 3 2 2 3]
 [2 7 4 5 8 5 4 7 1 1]
 [5 2 6 4 5 5 6 1 7 3]
 [6 1 4 1 3 3 6 1 4 6]
 [6 3 5 7 3 8 5 4 7 8]
 [4 1 6 7 5 2 4 6 4 5]
 [2 1 7 6 8 4 1 7 2 1]
 [6 8 8 2 8 8 1 1 3 4]
 [4 8 4 6 8 4 8 5 5 4]
 [5 2 8 3 7 5 1 5 2 6]]
1: [[6 5 9 4 2 5 4 3 3 4]
 [3 8 5 6 9 6 5 8 2 2]
 [6 3 7 5 6 6 7 2 8 4]
 [7 2 5 2 4 4 7 2 5 7]
 [7 4 6 8 4 9 6 5 8 9]
 [5 2 7 8 6 3 5 7 5 6]
 [3 2 8 7 9 5 2 8 3 2]
 [7 9 9 3 9 9 2 2 4 5]
 [5 9 5 7 9 5 9 6 6 5]
 [6 3 9 4 8 6 2 6 3 7]]
2: [[8 8 0 7 4 7 6 5 5 5]
 [5 0 8 9 0 8 7 0 5 4]
 [8 5 9 7 8 8 9 6 0 8]
 [8 4 8 5 7 6 9 6 0 0]
 [8 7 0 0 9 0 8 8 0 0]
 [6 6 0 0 0 8 8 9 8 9]
 [6 8 0 0 0 0 5 9 4 3]
 [0 0 0 0 0 0 7 4 5 6]
 [9 0 0 0 0 0 0 8 7 6]
 [8 7 0 0 0 0 6 8 4 8]]
3: [[0 0 5 0 9 0 0 8 6 6]
 [8 5 0 0 8 0 0 5 7 5]
 [9 9 0 0 0 0 0 0 3 9]
 [9 7 0 0 0 0 0 0 4 1]
 [9 9 3 5 0 8 0 0 6 3]
 [7 7 1 2 3 0 0 0 0 0]
 [7 9 1 1 2 5 0 0 0 9]
 [2 2 1 1 1 3 0 0 0 0]
 [0 4 2 1 1 2 5 0 0 0]
 [0 0 2 1 1 1 9 0 0 0]]
4: [[2 2 6 3 0 3 1 9 7 7]
 [0 9 2 3 0 3 1 6 9 7]
 [0 0 3 2 2 2 1

In [150]:
total_flashes

1656

In [160]:
total_flashes = 0
for i in range(1, 101):
    input_ += 1
    # phase 2
    while True:
        flashing_octopus = np.argwhere(input_ > 9)

        if not flashing_octopus.size:
            break

        for cell in flashing_octopus:
            update_adjacent_octopus(input_, *cell)

    # phase 3
    flashing_octopus = np.argwhere(input_ < 0)
    total_flashes += len(flashing_octopus)
    input_ = np.where(input_ < 0, 0, input_)

In [161]:
total_flashes

1702

Part Two

It seems like the individual flashes aren't bright enough to navigate. However, you might have a better option: the flashes seem to be synchronizing!

In the example above, the first time all octopuses flash simultaneously is step 195:

If you can calculate the exact moments when the octopuses will all flash simultaneously, you should be able to navigate through the cavern. What is the first step during which all octopuses flash?

In [187]:
step = 1
while True:
    demo_input += 1
    # phase 2
    while True:
        flashing_octopus = np.argwhere(demo_input > 9)

        if not flashing_octopus.size:
            break

        for cell in flashing_octopus:
            update_adjacent_octopus(demo_input, *cell)

    # phase 3
    flashing_octopus = np.argwhere(demo_input < 0)
    
    if len(flashing_octopus) == demo_input.size:
        print(f"All octopuses are flashing! After Step {step}.")
        break
        
    demo_input = np.where(demo_input < 0, 0, demo_input)
    step += 1

All octopuses are flashing! Step 194.


In [190]:
step = 1
while True:
    input_ += 1
    # phase 2
    while True:
        flashing_octopus = np.argwhere(input_ > 9)

        if not flashing_octopus.size:
            break

        for cell in flashing_octopus:
            update_adjacent_octopus(input_, *cell)

    # phase 3
    flashing_octopus = np.argwhere(input_ < 0)
    
    if len(flashing_octopus) == input_.size:
        print(f"All octopuses are flashing! After Step {step}.")
        break
        
    input_ = np.where(input_ < 0, 0, input_)
    step += 1

All octopuses are flashing! After Step 251.
